# Generated by Django 2.1.7 on 2019-04-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_ticketsetting_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
