# Generated by Django 2.1.7 on 2019-04-15 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('title', models.CharField(blank=True, default='', max_length=50, primary_key=True, serialize=False)),
                ('releaseDate', models.DateField(blank=True, null=True)),
                ('director', models.CharField(blank=True, default='', max_length=50)),
                ('summary', models.CharField(blank=True, default='', max_length=550)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/%m/%d/%Y')),
                ('cast', models.CharField(blank=True, default='', max_length=100)),
                ('rating', models.FloatField(blank=True, default=None, null=True)),
                ('genre', models.CharField(blank=True, default='', max_length=20)),
                ('trailer', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.MovieInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.MovieInfo')),
                ('showing', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Showing')),
            ],
        ),
    ]
