# Generated by Django 2.1.7 on 2019-04-15 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='showing',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.Showing'),
        ),
    ]
